export class PermisoModel {
    constructor(
        public puede_agregar_hito: boolean = false,
        public puede_editar_hito: boolean = false,
        public puede_eliminar_hito: boolean = false,
        public puede_validar_hito: boolean = false,
        public puede_desestimar_hito: boolean = false,
        public puede_comentar_hito: boolean = false,
        public puede_reactivar_estado_hito: boolean = false,
        public puede_agregar_avance: boolean = false,
        public puede_editar_avance: boolean = false,
        public puede_eliminar_avance: boolean = false,
        // public puede_validar_avance: boolean = false,
        public puede_desestimar_avance: boolean = false,
        public puede_comentar_avance: boolean = false,
        public puede_agregar_pedido: boolean = false,
        public puede_editar_pedido: boolean = false,
        public puede_eliminar_pedido: boolean = false,
        public puede_validar_pedido: boolean = false,
        public puede_comentar_pedido_pcm: boolean = false,
        public puede_agregar_acuerdo: boolean = false,
        public puede_agregar_acuerdo_mt: boolean = false,
        public puede_editar_acuerdo: boolean = false,
        public puede_eliminar_acuerdo: boolean = false,
        public puede_convertir_preacuerdo: boolean = false,
        public puede_solicitar_desestimacion: boolean = false,
        public puede_validar_avance_sector: boolean = false,
        public puede_validar_avance_pcm: boolean = false,
    ) { }
}
