import { DataResponses } from "./helpers.interface";

export interface PedidosResponses extends DataResponses {
  data: PedidoResponse[],
}

export interface PedidoResponse {
    // prioridadID?: string,
    // espacio: string,
    // sector: string,
    // ubigeo: string,
    // region: string,
    // provincia: string,
    // distrito: string,
    // objetivoEstrategicoTerritorial: string,
    // intervencionesEstrategicas: string,
    // aspectoCriticoResolver: string,
    // validado: string,
    // cuis: string,
    // cantidadPreAcuerdos: string,
    // cantidadAcuerdos: string,
    // eventoId: string,
    // sectorId: string,
    // depaid: string,
    // provid: string,
    // RowNumber: string,
    // tipoIntervencionId: string,
    // ejeEstrategicoId: string,
    // comentarioPCM: string,
    // estadoEspacio: string,
    // descripcionEstadoEspacio: string,
    // fechaEvento: string,
    // fechaFinEvento: string,
    // codigo: string,
    // bloquearRegistro: string,
    // tipoInversionId: string,
    prioridadID?: string,
    codigo: string,
    objetivoEstrategicoTerritorial: string,
    intervencionesEstrategicas: string,
    aspectoCriticoResolver: string,
    cuis: string,
    tipoIntervencionId: string,
    ejeEstrategicoId: string,
    comentarioPcm: string,
    tipoInversionId: string,
    cantidadPreAcuerdos: string,
    cantidadAcuerdos: string,
    tipoEventoId: string,
    tipoEvento: string,
    eventoId: string,
    evento: string,
    estadoEvento: string,
    fechaEvento: string,
    fechaFinEvento: string,
    sectorId: string,
    sector: string,
    ubigeo: string,
    departamento: string,
    provincia: string,
    distrito: string,
    validado: number,
}