import { SelectModel } from "../shared/select.model";

export class AcuerdoPedidoModel {
    constructor(
        public codigo?: string,
        public acuerdo?: string,
        public clasificacion?: string,
        public responsable?: string,
        public responsableSelect?: SelectModel,
        public plazo?: string,
        public espacio?: string,
        public sector?: string,
        public region?: string,
        public provincia?: string,
        public ubica?: string,
        public intervencionesEstrategicas?: string,
        public aspectoCriticoResolver?: string,
        public provid?: number,
        public cuis?: string,
        public ubigeo?: string,
        public acuerdoId?: number,
        public clasificacionId?: number,
        public responsableId?: number,
        public prioridadId?: number,
        public eventoId?: number,
        public prioridadTerritorial?: string,
        public objetivoEstrategicoTerritorial?: string,
        public depaid?: number,
        public sectorId?: number,
        public estadoRegistro?: number,
        public fechaCumplimiento?: Date,
        public nomEstadoRegistro?: string,
        public entidadId?: number,
        public entidad?: string,
        public entidadSelect?: SelectModel,
        public estadoRegistroInterno?: number,
        public tipo?: string,
        public estado?: string,
    ) { }
}
